project:
  type: website

website:
  title: "Redes Neuronales y Algoritmos Bioinspirados. Grupo 8"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: solar
    css: styles.css
    page-layout: full
    df-print: paged

editor: visual

